"""Bakes the two static assets of the storm replay scene (run once; the outputs are kept in this folder).

  terrain.bin      Int16 little-endian elevations in decimetres, row 0 = north, on a local equirectangular
                   grid (see terrainMeta.ts). Source: Terrain Tiles (Mapzen / Linux Foundation, on AWS Open
                   Data; terrarium encoding), https://registry.opendata.aws/terrain-tiles/ .
  waterways.json   Rivers and streams in the same box, simplified. Source: (c) OpenStreetMap contributors,
                   ODbL 1.0, via the Overpass API.

Usage: python bake_assets.py
"""
import io
import json
import math
import pathlib
import time

import numpy as np
import requests
from PIL import Image

HERE = pathlib.Path(__file__).parent
LON0, LON1 = -2.415, -2.160
LAT0, LAT1 = 51.262, 51.412
NX = 896  # grid columns; rows follow from the box's aspect in metres
Z = 13
UA = {"User-Agent": "Sayr hackathon bake script (OneAquaHealth IEEE hackathon)"}


def tile_xy(lon, lat, z):
    n = 2 ** z
    x = (lon + 180) / 360 * n
    y = (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n
    return x, y


def bake_terrain():
    latc = (LAT0 + LAT1) / 2
    kx = 111320 * math.cos(math.radians(latc))
    ky = 110540
    w_m = (LON1 - LON0) * kx
    h_m = (LAT1 - LAT0) * ky
    ny = round(NX * h_m / w_m)
    x0, y0 = tile_xy(LON0, LAT1, Z)
    x1, y1 = tile_xy(LON1, LAT0, Z)
    tx0, ty0, tx1, ty1 = int(x0), int(y0), int(x1), int(y1)
    mosaic = np.zeros(((ty1 - ty0 + 1) * 256, (tx1 - tx0 + 1) * 256), dtype=np.float64)
    for ty in range(ty0, ty1 + 1):
        for tx in range(tx0, tx1 + 1):
            url = f"https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{Z}/{tx}/{ty}.png"
            r = requests.get(url, headers=UA, timeout=60)
            r.raise_for_status()
            a = np.asarray(Image.open(io.BytesIO(r.content)).convert("RGB")).astype(np.float64)
            h = a[..., 0] * 256 + a[..., 1] + a[..., 2] / 256 - 32768
            mosaic[(ty - ty0) * 256:(ty - ty0 + 1) * 256, (tx - tx0) * 256:(tx - tx0 + 1) * 256] = h
    lons = LON0 + (np.arange(NX) + 0.5) / NX * (LON1 - LON0)
    lats = LAT1 - (np.arange(ny) + 0.5) / ny * (LAT1 - LAT0)
    px = np.array([tile_xy(lo, latc, Z)[0] for lo in lons]) - tx0
    py = np.array([tile_xy(LON0, la, Z)[1] for la in lats]) - ty0
    fx = px * 256 - 0.5
    fy = py * 256 - 0.5
    ix = np.clip(np.floor(fx).astype(int), 0, mosaic.shape[1] - 2)
    iy = np.clip(np.floor(fy).astype(int), 0, mosaic.shape[0] - 2)
    ax = (fx - ix)[None, :]
    ay = (fy - iy)[:, None]
    m = mosaic
    g = (m[iy][:, ix] * (1 - ax) * (1 - ay) + m[iy][:, ix + 1] * ax * (1 - ay)
         + m[iy + 1][:, ix] * (1 - ax) * ay + m[iy + 1][:, ix + 1] * ax * ay)
    dm = np.round(g * 10).astype("<i2")
    (HERE / "terrain.bin").write_bytes(dm.tobytes())
    meta = (
        "// Generated by bake_assets.py; do not edit. The grid of terrain.bin.\n"
        f"export const TERRAIN = {{ lon0: {LON0}, lon1: {LON1}, lat0: {LAT0}, lat1: {LAT1}, nx: {NX}, ny: {ny}, "
        f"minM: {float(g.min()):.1f}, maxM: {float(g.max()):.1f} }} as const;\n"
    )
    (HERE / "terrainMeta.ts").write_text(meta)
    print("terrain", NX, ny, "min", g.min(), "max", g.max(), "m, cell", round(w_m / NX, 1), "m")


def simplify(pts, tol):
    """Douglas-Peucker on local metres."""
    if len(pts) < 3:
        return pts
    latc = (LAT0 + LAT1) / 2
    kx = 111320 * math.cos(math.radians(latc))
    ky = 110540
    P = np.array([[p[0] * kx, p[1] * ky] for p in pts])
    keep = np.zeros(len(pts), bool)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        if b <= a + 1:
            continue
        d = P[b] - P[a]
        L = np.hypot(*d) or 1e-9
        seg = P[a + 1:b] - P[a]
        dist = np.abs(seg[:, 0] * d[1] - seg[:, 1] * d[0]) / L
        i = int(np.argmax(dist))
        if dist[i] > tol:
            k = a + 1 + i
            keep[k] = True
            stack += [(a, k), (k, b)]
    return [pts[i] for i in range(len(pts)) if keep[i]]


def bake_waterways():
    q = f"""[out:json][timeout:120];
(way["waterway"~"^(river|stream|brook|drain|ditch)$"]({LAT0},{LON0},{LAT1},{LON1}););
out geom;"""
    for attempt in range(4):
        r = requests.post("https://overpass-api.de/api/interpreter", data={"data": q}, headers=UA, timeout=180)
        if r.status_code == 200:
            break
        time.sleep(10 * (attempt + 1))
    r.raise_for_status()
    ways = []
    for el in r.json()["elements"]:
        kind = el["tags"].get("waterway")
        pts = [[round(g["lon"], 5), round(g["lat"], 5)] for g in el.get("geometry", [])]
        if len(pts) < 2:
            continue
        k = "river" if kind == "river" else "stream" if kind in ("stream", "brook") else "minor"
        pts = simplify(pts, 6.0)
        ways.append({"k": k, "n": el["tags"].get("name", ""), "c": pts})
    out = {
        "source": "Waterways (c) OpenStreetMap contributors, ODbL 1.0, via the Overpass API",
        "bbox": [LON0, LAT0, LON1, LAT1],
        "ways": ways,
    }
    (HERE / "waterways.json").write_text(json.dumps(out, separators=(",", ":")))
    print("waterways", len(ways), "ways", sum(len(w["c"]) for w in ways), "points")


if __name__ == "__main__":
    bake_terrain()
    bake_waterways()
