// Generated by bake_assets.py; do not edit. The grid of terrain.bin.
export const TERRAIN = { lon0: -2.415, lon1: -2.16, lat0: 51.262, lat1: 51.412, nx: 896, ny: 838, minM: 13.8, maxM: 231.5 } as const;
